# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: atlassianlabs/docker-node-jdk-chrome-firefox
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - run: curl -sL https://deb.nodesource.com/setup_11.x | bash - && apt-get install -y nodejs
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # - run: sudo apt-get install -y libappindicator1 fonts-liberation & wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb & sudo dpkg -i google-chrome*.deb

      - run: npm ci && npx shadow-cljs info

      - save_cache:
          paths:
            - node_modules
            - .m2
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test
